[project]
name = "scrapingdog-mcp-server"
dynamic = ["version"]
description = "A MCP server for Scrapingdog"
keywords = ["scrapingdog", "mcp", "server", "google", "search", "scraping"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.16",
    "certifi>=2025.1.31",
    "mcp[cli]>=1.27.1",
    "pydantic>=2.11.2",
    "python-dotenv>=1.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "basedpyright",
]

[project.urls]
"Homepage" = "https://github.com/hunmonk/scrapingdog-mcp-server"
"Bug Tracker" = "https://github.com/hunmonk/scrapingdog-mcp-server/issues"

[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.basedpyright]
include = ["src", "tests"]
exclude = ["src/*.egg-info"]

[project.scripts]
scrapingdog-mcp-server = "scrapingdog_mcp_server:main"
